"""Failure classification (v0.3, superset of v0.2)."""
from __future__ import annotations


MODEL_OUTPUT_ERROR = "MODEL_OUTPUT_ERROR"
VALIDATION_ERROR = "VALIDATION_ERROR"
SANDBOX_VIOLATION = "SANDBOX_VIOLATION"
APPROVAL_DENIED = "APPROVAL_DENIED"
EXECUTION_ERROR = "EXECUTION_ERROR"
TIMEOUT = "TIMEOUT"
OLLAMA_ERROR = "OLLAMA_ERROR"
TEST_FAILURE = "TEST_FAILURE"
MAX_STEPS_REACHED = "MAX_STEPS_REACHED"
REVIEW_REJECTED = "REVIEW_REJECTED"
REVISION_EXHAUSTED = "REVISION_EXHAUSTED"
CANCELLED = "CANCELLED"
ROLLBACK_FAILED = "ROLLBACK_FAILED"
INTERNAL_PROTECTED = "INTERNAL_PROTECTED"
# v0.4 additions
LOOP_DETECTED = "LOOP_DETECTED"
ESCALATED = "ESCALATED"
INTERRUPTED = "INTERRUPTED"
COLLISION_DENIED = "COLLISION_DENIED"
ORACLE_SUSPICIOUS = "ORACLE_SUSPICIOUS"
IDEMPOTENT_REPLAY = "IDEMPOTENT_REPLAY"
# v0.6 additions
REVIEWER_EVIDENCE_CONFLICT = "REVIEWER_EVIDENCE_CONFLICT"
REVIEWER_UNRELIABLE_FOR_THIS_DECISION = "REVIEWER_UNRELIABLE_FOR_THIS_DECISION"
MILESTONE_INCOMPLETE = "MILESTONE_INCOMPLETE"
NO_PROGRESS_DETECTED = "NO_PROGRESS_DETECTED"
ADMIN_REQUIRED = "ADMIN_REQUIRED"
EMERGENCY_STOPPED = "EMERGENCY_STOPPED"

ALL_FAILURES = (
    MODEL_OUTPUT_ERROR, VALIDATION_ERROR, SANDBOX_VIOLATION, APPROVAL_DENIED,
    EXECUTION_ERROR, TIMEOUT, OLLAMA_ERROR, TEST_FAILURE, MAX_STEPS_REACHED,
    REVIEW_REJECTED, REVISION_EXHAUSTED, CANCELLED, ROLLBACK_FAILED,
    INTERNAL_PROTECTED, LOOP_DETECTED, ESCALATED, INTERRUPTED,
    COLLISION_DENIED, ORACLE_SUSPICIOUS, IDEMPOTENT_REPLAY,
    REVIEWER_EVIDENCE_CONFLICT, REVIEWER_UNRELIABLE_FOR_THIS_DECISION,
    MILESTONE_INCOMPLETE, NO_PROGRESS_DETECTED, ADMIN_REQUIRED,
    EMERGENCY_STOPPED,
)


class FailureTracker:
    """Terminates infinite retry loops: counts consecutive identical failures."""

    def __init__(self, repeat_threshold: int = 3):
        self.threshold = max(1, repeat_threshold)
        self._last_key: str | None = None
        self._run = 0

    def note(self, key: str) -> int:
        if key == self._last_key:
            self._run += 1
        else:
            self._last_key = key
            self._run = 1
        return self._run

    def note_success(self) -> None:
        self._last_key = None
        self._run = 0

    def exceeded(self) -> bool:
        return self._run >= self.threshold
