"""Aetherius Data Service Registry - Pre-populated entries (§53).

All applications from the recommended install set (§53), with accurate states
based on live inventory. Only verified-installed services are VERIFIED.
Others are NOT_INSTALLED or EVALUATION.

This is project configuration data — no secrets.
"""
import os

from data_fabric.data_service_registry import (
    DataServiceRegistry, DataServiceEntry,
    AppState, SourceModel, SourceType, DataClass,
)


def _resolve_user_local_path(relative: str) -> str:
    """Resolve a per-user LOCALAPPDATA path without hardcoding a username.

    The repository is PUBLIC and `tests/test_secret_hygiene.py` rejects
    personal absolute paths in source, so no `C:/Users/<name>/...` literal
    may appear here. Returns the resolved path when the target exists and
    the template path otherwise (state stays accurate, source stays clean).
    """
    base = os.environ.get("LOCALAPPDATA", "")
    if base:
        candidate = os.path.join(base, *relative.split("/"))
        if os.path.isfile(candidate):
            return candidate.replace("\\", "/")
    return "%LOCALAPPDATA%/" + relative


def build_default_registry() -> DataServiceRegistry:
    """Build the canonical registry with all §53 services pre-registered."""
    reg = DataServiceRegistry()

    services = [
        # === §7: Credential / Password Stack ===
        DataServiceEntry(
            service_id="keepass-canonical",
            name="KeePass",
            category="password_manager",
            source_model=SourceModel.LOCAL,
            source_type=SourceType.OPEN_SOURCE,
            pricing="free",
            state=AppState.PRIMARY,
            installed_version="2.x",
            installation_path="C:/Program Files/KeePass Password Safe 2/KeePass.exe",
            account_required=False,
            account_state="NOT_REQUIRED",
            primary_role="canonical credential vault",
            data_classes=[DataClass.CREDENTIALS.value, DataClass.TWO_FACTOR.value,
                          DataClass.IDENTITY.value, DataClass.BUSINESS.value],
            privacy_ceiling="SECRET_LOCAL_ONLY",
            encryption="AES-256 local",
            sync="none_inherent",
            backup="manual_database_file",
            export_formats=[".kdbx"],
            has_api=False,
            has_cli=True,
            automation_support=False,
            agent_support=True,
            credential_refs=["CRED-KEEPASS-MASTER"],
            storage_location="local_filesystem",
            backup_policy={"type": "manual", "frequency": "before_rotation"},
            health="VERIFIED_LIVE",
            last_verified=None,
            evidence={"keepass_found_at": "C:/Program Files/KeePass Password Safe 2/KeePass.exe"},
            installation_group="DESKTOP_LIGHTWEIGHT",
            docker_compose_path=None,
            firewall_required=False,
        ),
        DataServiceEntry(
            service_id="keepassxc",
            name="KeePassXC",
            category="password_manager",
            source_model=SourceModel.LOCAL,
            source_type=SourceType.OPEN_SOURCE,
            pricing="free",
            state=AppState.NOT_INSTALLED,
            account_required=False,
            account_state="NONE",
            data_classes=[DataClass.CREDENTIALS.value],
            privacy_ceiling="SECRET_LOCAL_ONLY",
            encryption="AES-256 local",
            sync="via_cloud_folder",
            has_cli=True,
            has_api=False,
            agent_support=True,
            download_source="https://keepassxc.org/download/",
            installation_group="DESKTOP_LIGHTWEIGHT",
        ),
        DataServiceEntry(
            service_id="bitwarden",
            name="Bitwarden",
            category="password_manager",
            source_model=SourceModel.HOSTED,
            source_type=SourceType.OPEN_SOURCE,
            pricing="freemium",
            state=AppState.EVALUATION,
            account_required=True,
            account_state="OWNER_ACTION_REQUIRED",
            data_classes=[DataClass.CREDENTIALS.value, DataClass.TWO_FACTOR.value],
            privacy_ceiling="PRIVACY_PUBLIC",
            encryption="E2E encrypted",
            sync="cloud",
            export_formats=["CSV", "JSON"],
            has_cli=True,
            has_api=True,
            automation_support=True,
            agent_support=True,
            download_source="https://bitwarden.com/download/",
            installation_group="DESKTOP_LIGHTWEIGHT",
        ),
        DataServiceEntry(
            service_id="proton-pass",
            name="Proton Pass",
            category="password_manager",
            source_model=SourceModel.HOSTED,
            source_type=SourceType.CLOSED_SOURCE,
            pricing="freemium",
            state=AppState.NOT_INSTALLED,
            account_required=True,
            account_state="NONE",
            data_classes=[DataClass.CREDENTIALS.value, DataClass.TWO_FACTOR.value],
            privacy_ceiling="PRIVACY_PROJECT",
            encryption="E2E encrypted",
            sync="cloud",
            export_formats=["CSV"],
            has_cli=False,
            has_api=True,
            automation_support=True,
            agent_support=True,
            download_source="https://proton.me/pass/download",
            installation_group="DESKTOP_LIGHTWEIGHT",
            evidence={"note": "Agent access tokens available on paid plans (§8 note)"},
        ),
        # === §9: Two-Factor Authentication ===
        DataServiceEntry(
            service_id="ente-auth",
            name="Ente Auth",
            category="authenticator",
            source_model=SourceModel.HOSTED,
            source_type=SourceType.OPEN_SOURCE,
            pricing="freemium",
            state=AppState.NOT_INSTALLED,
            account_required=True,
            account_state="NONE",
            data_classes=[DataClass.TWO_FACTOR.value],
            privacy_ceiling="PRIVACY_CONFIDENTIAL",
            encryption="E2E encrypted",
            sync="cloud",
            export_formats=["JSON"],
            has_cli=False,
            has_api=True,
            automation_support=False,
            download_source="https://ente.io/download",
            installation_group="MOBILE_RECOMMENDED",
            evidence={"note": "Free OSS with E2E encrypted cross-device 2FA backups"},
        ),
        # === §10: Secure Email ===
        DataServiceEntry(
            service_id="proton-mail",
            name="Proton Mail",
            category="email",
            source_model=SourceModel.HOSTED,
            source_type=SourceType.CLOSED_SOURCE,
            pricing="freemium",
            state=AppState.NOT_INSTALLED,
            account_required=True,
            account_state="NONE",
            data_classes=[DataClass.EMAIL.value, DataClass.IDENTITY.value],
            privacy_ceiling="PRIVACY_CONFIDENTIAL",
            encryption="E2E encrypted",
            sync="cloud",
            export_formats=["MBOX", "EML"],
            has_cli=False,
            has_api=True,
            download_source="https://proton.me/mail/download",
            installation_group="DESKTOP_LIGHTWEIGHT",
        ),
        DataServiceEntry(
            service_id="tuta",
            name="Tuta",
            category="email",
            source_model=SourceModel.HOSTED,
            source_type=SourceType.CLOSED_SOURCE,
            pricing="freemium",
            state=AppState.NOT_INSTALLED,
            account_required=True,
            account_state="NONE",
            data_classes=[DataClass.EMAIL.value],
            privacy_ceiling="PRIVACY_CONFIDENTIAL",
            encryption="E2E encrypted",
            sync="cloud",
            export_formats=["EML"],
            has_cli=False,
            has_api=True,
            download_source="https://tuta.com/download",
            installation_group="DESKTOP_LIGHTWEIGHT",
        ),
        DataServiceEntry(
            service_id="thunderbird",
            name="Thunderbird",
            category="email_client",
            source_model=SourceModel.LOCAL,
            source_type=SourceType.OPEN_SOURCE,
            pricing="free",
            state=AppState.NOT_INSTALLED,
            data_classes=[DataClass.EMAIL.value],
            privacy_ceiling="PRIVACY_PROJECT",
            encryption="TLS",
            sync="IMAP/POP",
            has_cli=True,
            download_source="https://www.thunderbird.net/",
            installation_group="DESKTOP_LIGHTWEIGHT",
        ),
        # === §11: Calendar + Contacts ===
        DataServiceEntry(
            service_id="proton-calendar",
            name="Proton Calendar",
            category="calendar",
            source_model=SourceModel.HOSTED,
            source_type=SourceType.CLOSED_SOURCE,
            pricing="freemium",
            state=AppState.NOT_INSTALLED,
            account_required=True,
            account_state="NONE",
            data_classes=[DataClass.CALENDAR.value, DataClass.CONTACTS.value],
            privacy_ceiling="PRIVACY_PROJECT",
            encryption="E2E encrypted",
            sync="cloud",
            export_formats=["ICS", "CSV"],
        ),
        DataServiceEntry(
            service_id="nextcloud-contacts",
            name="Nextcloud Contacts/Calendar",
            category="calendar_contacts",
            source_model=SourceModel.SELF_HOSTED,
            source_type=SourceType.OPEN_SOURCE,
            pricing="self_hosted",
            state=AppState.NOT_INSTALLED,
            data_classes=[DataClass.CALENDAR.value, DataClass.CONTACTS.value],
            privacy_ceiling="PRIVACY_PROJECT",
            sync="CalDAV/CardDAV",
            export_formats=["ICS", "VCF", "CSV"],
            docker_compose_path="future: nextcloud",
            installation_group="DOCKER_SELF_HOSTED",
        ),
        # === §12: File Storage ===
        DataServiceEntry(
            service_id="proton-drive",
            name="Proton Drive",
            category="cloud_storage",
            source_model=SourceModel.HOSTED,
            source_type=SourceType.CLOSED_SOURCE,
            pricing="freemium",
            state=AppState.NOT_INSTALLED,
            account_required=True,
            account_state="OWNER_ACTION_REQUIRED",
            data_classes=[DataClass.FILES.value],
            privacy_ceiling="PRIVACY_PROJECT",
            encryption="E2E encrypted at rest",
            sync="cloud",
            download_source="https://proton.me/drive/download",
        ),
        DataServiceEntry(
            service_id="cryptomator",
            name="Cryptomator",
            category="file_encryption",
            source_model=SourceModel.LOCAL,
            source_type=SourceType.OPEN_SOURCE,
            pricing="free",
            state=AppState.NOT_INSTALLED,
            data_classes=[DataClass.FILES.value, DataClass.PHOTOS.value],
            privacy_ceiling="PRIVACY_SECRET_LOCAL_ONLY",
            encryption="AES-256 vault encryption",
            sync="via_cloud_folder",
            has_cli=True,
            download_source="https://cryptomator.org/downloads/",
            installation_group="DESKTOP_LIGHTWEIGHT",
        ),
        DataServiceEntry(
            service_id="veracrypt",
            name="VeraCrypt",
            category="disk_encryption",
            source_model=SourceModel.LOCAL,
            source_type=SourceType.OPEN_SOURCE,
            pricing="free",
            state=AppState.NOT_INSTALLED,
            data_classes=[DataClass.FILES.value, DataClass.DOCUMENTS.value,
                          DataClass.IDENTITY.value, DataClass.LEGAL.value],
            privacy_ceiling="SECRET_LOCAL_ONLY",
            encryption="AES-256/Twofish/Serpent",
            download_source="https://www.veracrypt.fr/en/Downloads.html",
            installation_group="DESKTOP_LIGHTWEIGHT",
        ),
        DataServiceEntry(
            service_id="nextcloud",
            name="Nextcloud",
            category="self_hosted_cloud",
            source_model=SourceModel.SELF_HOSTED,
            source_type=SourceType.OPEN_SOURCE,
            pricing="self_hosted",
            state=AppState.NOT_INSTALLED,
            data_classes=[DataClass.FILES.value, DataClass.CALENDAR.value,
                          DataClass.CONTACTS.value, DataClass.DOCUMENTS.value],
            privacy_ceiling="PRIVACY_PROJECT",
            sync="self_hosted",
            docker_compose_path="future: nextcloud",
            installation_group="DOCKER_SELF_HOSTED",
        ),
        DataServiceEntry(
            service_id="syncthing",
            name="Syncthing",
            category="p2p_sync",
            source_model=SourceModel.PEER_TO_PEER,
            source_type=SourceType.OPEN_SOURCE,
            pricing="free",
            state=AppState.NOT_INSTALLED,
            data_classes=[DataClass.FILES.value],
            privacy_ceiling="PRIVACY_PROJECT",
            sync="P2P",
            has_cli=True,
            download_source="https://github.com/syncthing/syncthing/releases",
            installation_group="DESKTOP_BACKGROUND",
            evidence={"warning": "Sync IS NOT backup (§30)"},
        ),
        # === §15: Notes ===
        DataServiceEntry(
            service_id="joplin",
            name="Joplin",
            category="notes",
            source_model=SourceModel.LOCAL,
            source_type=SourceType.OPEN_SOURCE,
            pricing="free",
            state=AppState.NOT_INSTALLED,
            data_classes=[DataClass.NOTES.value, DataClass.DOCUMENTS.value,
                          DataClass.PROJECTS.value],
            privacy_ceiling="PRIVACY_PROJECT",
            encryption="E2E optional",
            sync="via_cloud_folder/Nextcloud",
            export_formats=["Markdown", "JEX", "RAW"],
            has_cli=True,
            has_api=True,
            download_source="https://joplinapp.org/",
            installation_group="DESKTOP_LIGHTWEIGHT",
        ),
        # === §16: Finance ===
        DataServiceEntry(
            service_id="actual-budget",
            name="Actual Budget",
            category="finance",
            source_model=SourceModel.LOCAL,
            source_type=SourceType.OPEN_SOURCE,
            pricing="free",
            state=AppState.NOT_INSTALLED,
            data_classes=[DataClass.FINANCE.value, DataClass.BUSINESS.value],
            privacy_ceiling="SECRET_LOCAL_ONLY",
            encryption="local",
            sync="self_hosted",
            has_cli=True,
            docker_compose_path="future: actual",
            installation_group="DOCKER_SELF_HOSTED",
            credential_refs=[],
            evidence={"warning": "No auto bank sync without explicit owner approval (§16)"},
        ),
        DataServiceEntry(
            service_id="gnucash",
            name="GnuCash",
            category="finance",
            source_model=SourceModel.LOCAL,
            source_type=SourceType.OPEN_SOURCE,
            pricing="free",
            state=AppState.NOT_INSTALLED,
            data_classes=[DataClass.FINANCE.value, DataClass.BUSINESS.value],
            privacy_ceiling="SECRET_LOCAL_ONLY",
            encryption="local file",
            sync="manual",
            download_source="https://www.gnucash.org/",
            installation_group="DESKTOP_LIGHTWEIGHT",
        ),
        DataServiceEntry(
            service_id="firefly-iii",
            name="Firefly III",
            category="finance",
            source_model=SourceModel.SELF_HOSTED,
            source_type=SourceType.OPEN_SOURCE,
            pricing="self_hosted",
            state=AppState.NOT_INSTALLED,
            data_classes=[DataClass.FINANCE.value],
            privacy_ceiling="PRIVACY_CONFIDENTIAL",
            docker_compose_path="future: firefly-iii",
            installation_group="DOCKER_SELF_HOSTED",
        ),
        # === §19-22: Messaging ===
        DataServiceEntry(
            service_id="signal",
            name="Signal",
            category="messaging",
            source_model=SourceModel.HOSTED,
            source_type=SourceType.OPEN_SOURCE,
            pricing="free",
            state=AppState.NOT_INSTALLED,
            account_required=True,
            account_state="OWNER_ACTION_REQUIRED",
            data_classes=[DataClass.MESSAGING.value, DataClass.SOCIAL.value],
            privacy_ceiling="PRIVACY_SECRET_LOCAL_ONLY",
            encryption="E2E encrypted",
            download_source="https://signal.org/download/",
        ),
        DataServiceEntry(
            service_id="element",
            name="Element (Matrix)",
            category="messaging",
            source_model=SourceModel.FEDERATED,
            source_type=SourceType.OPEN_SOURCE,
            pricing="free",
            state=AppState.NOT_INSTALLED,
            account_required=True,
            account_state="OWNER_ACTION_REQUIRED",
            data_classes=[DataClass.MESSAGING.value, DataClass.SOCIAL.value],
            privacy_ceiling="PRIVACY_PROJECT",
            encryption="E2E optional (Olm/Megolm)",
            sync="federated",
            has_cli=True,
            has_api=True,
            download_source="https://element.io/download",
            installation_group="DESKTOP_LIGHTWEIGHT",
            evidence={"note": "Matrix protocol supports VoIP signalling, bots, bridges (§20)"},
        ),
        DataServiceEntry(
            service_id="jami",
            name="Jami",
            category="messaging",
            source_model=SourceModel.PEER_TO_PEER,
            source_type=SourceType.OPEN_SOURCE,
            pricing="free",
            state=AppState.NOT_INSTALLED,
            data_classes=[DataClass.MESSAGING.value, DataClass.SOCIAL.value],
            privacy_ceiling="PRIVACY_SECRET_LOCAL_ONLY",
            encryption="E2E P2P",
            sync="P2P",
            has_cli=True,
            download_source="https://www.jami.net/",
            installation_group="DESKTOP_LIGHTWEIGHT",
        ),
        DataServiceEntry(
            service_id="simplex",
            name="SimpleX",
            category="messaging",
            source_model=SourceModel.DECENTRALISED,
            source_type=SourceType.OPEN_SOURCE,
            pricing="free",
            state=AppState.NOT_INSTALLED,
            account_required=True,
            account_state="NONE",
            data_classes=[DataClass.MESSAGING.value, DataClass.SOCIAL.value],
            privacy_ceiling="PRIVACY_SECRET_LOCAL_ONLY",
            encryption="E2E encrypted",
            download_source="https://simplex.chat/",
            installation_group="DESKTOP_LIGHTWEIGHT",
        ),
        # === §23: Documents ===
        DataServiceEntry(
            service_id="paperless-ngx",
            name="Paperless-ngx",
            category="document_management",
            source_model=SourceModel.SELF_HOSTED,
            source_type=SourceType.OPEN_SOURCE,
            pricing="self_hosted",
            state=AppState.NOT_INSTALLED,
            data_classes=[DataClass.DOCUMENTS.value, DataClass.LEGAL.value,
                          DataClass.IDENTITY.value],
            privacy_ceiling="PRIVACY_SECRET_LOCAL_ONLY",
            docker_compose_path="future: paperless-ngx",
            installation_group="DOCKER_SELF_HOSTED",
        ),
        # === §26-27: Backup ===
        DataServiceEntry(
            service_id="restic",
            name="Restic",
            category="backup",
            source_model=SourceModel.LOCAL,
            source_type=SourceType.OPEN_SOURCE,
            pricing="free",
            state=AppState.NOT_INSTALLED,
            data_classes=[DataClass.BACKUPS.value],
            privacy_ceiling="SECRET_LOCAL_ONLY",
            encryption="AES-256 repo encryption",
            has_cli=True,
            automation_support=True,
            download_source="https://restic.net/",
            installation_group="CLI",
        ),
        DataServiceEntry(
            service_id="kopia",
            name="Kopia",
            category="backup",
            source_model=SourceModel.LOCAL,
            source_type=SourceType.OPEN_SOURCE,
            pricing="free",
            state=AppState.NOT_INSTALLED,
            data_classes=[DataClass.BACKUPS.value],
            privacy_ceiling="SECRET_LOCAL_ONLY",
            encryption="AES-256",
            has_cli=True,
            download_source="https://kopia.org/",
            installation_group="CLI",
        ),
        DataServiceEntry(
            service_id="duplicati",
            name="Duplicati",
            category="backup",
            source_model=SourceModel.LOCAL,
            source_type=SourceType.OPEN_SOURCE,
            pricing="free",
            state=AppState.NOT_INSTALLED,
            data_classes=[DataClass.BACKUPS.value],
            privacy_ceiling="PRIVACY_SECRET_LOCAL_ONLY",
            encryption="AES-256",
            has_cli=True,
            download_source="https://www.duplicati.com/",
            installation_group="DESKTOP_LIGHTWEIGHT",
        ),
        # === §32: Remote Network ===
        DataServiceEntry(
            service_id="wireguard",
            name="WireGuard",
            category="vpn",
            source_model=SourceModel.LOCAL,
            source_type=SourceType.OPEN_SOURCE,
            pricing="free",
            state=AppState.NOT_INSTALLED,
            data_classes=[DataClass.MESSAGING.value, DataClass.SOCIAL.value],
            privacy_ceiling="PRIVACY_SECRET_LOCAL_ONLY",
            encryption="ChaCha20/Poly1305",
            has_cli=True,
            firewall_required=True,
            download_source="https://www.wireguard.com/install/",
            installation_group="DESKTOP_LIGHTWEIGHT",
        ),
        # === §31: Browser/Bookmarks ===
        DataServiceEntry(
            service_id="linkwarden",
            name="Linkwarden",
            category="bookmarks",
            source_model=SourceModel.SELF_HOSTED,
            source_type=SourceType.OPEN_SOURCE,
            pricing="self_hosted",
            state=AppState.NOT_INSTALLED,
            data_classes=[DataClass.RESEARCH.value, DataClass.NOTES.value],
            privacy_ceiling="PRIVACY_PROJECT",
            docker_compose_path="future: linkwarden",
            has_api=True,
            installation_group="DOCKER_SELF_HOSTED",
        ),
        # === §28: Repositories ===
        DataServiceEntry(
            service_id="github",
            name="GitHub",
            category="git_remote",
            source_model=SourceModel.HOSTED,
            source_type=SourceType.CLOSED_SOURCE,
            pricing="freemium",
            state=AppState.VERIFIED,
            account_required=True,
            data_classes=[DataClass.SOURCE_CODE.value, DataClass.PROJECTS.value],
            privacy_ceiling="PRIVACY_PUBLIC",
            sync="cloud",
            has_cli=True,
            has_api=True,
            automation_support=True,
            account_state="VERIFIED_LIVE",
            evidence={"github_user": "jayprophit", "gh_cli_authenticated": True},
            installation_group="CLI",
        ),
        # === §29: Self-hosted platform ===
        DataServiceEntry(
            service_id="docker",
            name="Docker",
            category="container_runtime",
            source_model=SourceModel.LOCAL,
            source_type=SourceType.CLOSED_SOURCE,
            pricing="freemium",
            state=AppState.VERIFIED,
            installed_version="29.7.2",
            installation_path="C:/Program Files/Docker/Docker/Docker Desktop.exe",
            data_classes=[DataClass.SOURCE_CODE.value, DataClass.BACKUPS.value],
            privacy_ceiling="PRIVACY_PROJECT",
            has_cli=True,
            automation_support=True,
            evidence={"docker_version": "v29.7.2", "docker_verified": True},
            installation_group="DESKTOP_BACKGROUND",
        ),
        DataServiceEntry(
            service_id="wsl",
            name="WSL",
            category="linux_subsystem",
            source_model=SourceModel.LOCAL,
            source_type=SourceType.OPEN_SOURCE,
            pricing="free",
            state=AppState.VERIFIED,
            installed_version="2.7.14",
            data_classes=[DataClass.SOURCE_CODE.value, DataClass.FILES.value],
            privacy_ceiling="PRIVACY_PROJECT",
            has_cli=True,
            evidence={"wsl_version": "2.7.14", "verified": True},
            installation_group="SYSTEM",
        ),
        # === GitHub Desktop (already installed) ===
        DataServiceEntry(
            service_id="github-desktop",
            name="GitHub Desktop",
            category="git_client",
            source_model=SourceModel.LOCAL,
            source_type=SourceType.CLOSED_SOURCE,
            pricing="free",
            state=AppState.INSTALLED,
            # Resolved at load time, never hardcoded: the repo is PUBLIC and
            # personal absolute paths are a hygiene violation.
            installation_path=_resolve_user_local_path("GitHubDesktop/GitHubDesktop.exe"),
            data_classes=[DataClass.SOURCE_CODE.value],
            privacy_ceiling="PRIVACY_PROJECT",
            has_cli=True,
            installation_group="DESKTOP_LIGHTWEIGHT",
        ),
    ]

    for svc in services:
        reg.register(svc)

    return reg

def load_or_build_registry(path: str) -> DataServiceRegistry:
    """Load registry from JSON if exists, else build default."""
    if os.path.isfile(path):
        try:
            return DataServiceRegistry.from_json(path)
        except Exception:
            pass
    return build_default_registry()
